# Generated by Django 5.1.2 on 2024-10-30 21:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('consumption', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)])),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openei_id', models.CharField(max_length=100)),
                ('rate_name', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('pricing_matrix', models.JSONField()),
                ('average_rate', models.FloatField()),
                ('first_year_cost', models.FloatField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_utility', to='app.project')),
            ],
        ),
    ]
