# Generated by Django 5.1.2 on 2024-10-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalutility',
            name='pricing_matrix',
            field=models.JSONField(blank=True, help_text='Stores the complete rate structure including time periods and tiers', null=True),
        ),
    ]
